nationalities = ['Algerian', 'American', 'Argentinian', 'Australian', 'Austrian', 'Bahraini', 'Bangladeshi',
                'Belarusian', 'Belgian', 'Beninese', 'Bolivian', 'Brazilian', 'British', 'Bruneian', 'Bulgarian',
                'Burkinabe', 'Burmese', 'Cambodian', 'Cameroonian', 'Canadian', 'Chilean', 'Chinese', 'Colombian',
                'Congolese', 'Croatian', 'Cypriot', 'Czech', 'Danish', 'Dominican', 'Dutch', 'Egyptian', 'Emirati',
                'Eritrean', 'Estonian', 'Ethiopian', 'Filipino', 'Finnish', 'French', 'German', 'Ghanaian', 'Greek',
                'Haitian', 'Honduran', 'Hong Konger', 'Hungarian', 'Icelandic', 'Indian', 'Indonesian', 'Iranian',
                'Iraqi', 'Irish', 'Israeli', 'Italian', 'Ivorian', 'Japanese', 'Jordanian', 'Kazakh', 'Kenyan',
                'Kuwaiti', 'Kyrgyz', 'Laotian', 'Latvian', 'Lebanese', 'Liberian', 'Libyan', 'Liechtensteiner',
                'Lithuanian', 'Malagasy', 'Malaysian', 'Malian', 'Maltese', 'Mauritanian', 'Mauritian', 'Mexican',
                'Moldovan', 'Mongolian', 'Moroccan', 'Mozambican', 'Nepali', 'New Zealand', 'Nicaraguan', 'Nigerian',
                'Nigerien', 'North Korean', 'Norwegian', 'Omani', 'Pakistani', 'Palestinian', 'Panamanian',
                'Paraguayan', 'Peruvian', 'Polish', 'Portuguese', 'Qatari', 'Romanian', 'Russian', 'Rwandan',
                'Salvadoran', 'Saudi Arabian', 'Senegalese', 'Sierra Leonean', 'Singaporean', 'Slovak', 'Slovenian',
                'Somali', 'South African', 'South Korean', 'Spanish', 'Sri Lankan', 'Sudanese', 'Swedish', 'Swiss',
                'Syrian', 'Taiwanese', 'Tajik', 'Tanzanian', 'Thai', 'Tunisian', 'Turkish', 'Ugandan', 'Ukrainian',
                'Uruguayan', 'Uzbek', 'Venezuelan', 'Vietnamese', 'Yemeni', 'Zimbabwean']

countries = ['Algeria', 'Argentina', 'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Benin',
            'Bolivia', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada', 'China',
            'Colombia', 'Croatia', 'Cyprus', 'Czech Republic', "Côte d'Ivoire", 'DR Congo', 'Denmark',
            'Dominican Republic', 'Egypt', 'El Salvador', 'Eritrea', 'Estonia', 'Ethiopia', 'Finland', 'France',
            'Germany', 'Ghana', 'Greece', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
            'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait',
            'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
            'Malaysia', 'Mali', 'Malta', 'Mauritania', 'Mexico', 'Moldova', 'Mongolia', 'Morocco', 'Mozambique',
            'Myanmar', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'Norway',
            'Oman', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
            'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia', 'Senegal', 'Sierra Leone', 'Singapore', 'Slovakia',
            'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden',
            'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tunisia', 'Turkey', 'Turkmenistan',
            'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
            'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe']

cities = {
    'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Batna', 'Blida', 'Setif', 'Tlemcen', 'Bejaia', 'Biskra'],
    'Argentina': ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza', 'Tucuman', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
    'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Canberra', 'Sunshine Coast', 'Wollongong', 'Hobart', 'Geelong', 'Townsville', 'Cairns', 'Darwin', 'Toowoomba', 'Ballarat', 'Bendigo', 'Albury-Wodonga', 'Launceston'],
    'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Steyr', 'Dornbirn', 'Wiener Neustadt', 'Feldkirch', 'Bregenz', 'Wolfsberg', 'Baden', 'Klosterneuburg', 'Leoben', 'Leonding', 'Traun', 'Krems'],
    'Bahrain': ['Manama', 'Muharraq', 'Riffa', 'Hamad Town', 'A\'ali', 'Isa Town', 'Sitra', 'Budaiya', 'Jidhafs', 'Al-Malikiyah'],
    'Bangladesh': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Comilla', 'Narayanganj', 'Sylhet', 'Barisal', 'Rangpur', 'Mymensingh'],
    'Belarus': ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno', 'Brest', 'Bobruisk', 'Baranovichi', 'Borisov', 'Pinsk'],
    'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liege', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst', 'Mechelen', 'La Louviere', 'Kortrijk', 'Hasselt', 'Ostend', 'Sint-Niklaas', 'Tournai', 'Genk', 'Seraing', 'Roeselare'],
    'Benin': ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon', 'Kandi', 'Lokossa', 'Ouidah', 'Abomey-Calavi', 'Natitingou'],
    'Bolivia': ['Santa Cruz de la Sierra', 'El Alto', 'La Paz', 'Cochabamba', 'Oruro', 'Sucre', 'Tarija', 'Potosi', 'Sacaba', 'Montero'],
    'Brazil': ['Sao Paulo', 'Rio de Janeiro', 'Salvador', 'Brasilia', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belem', 'Goiania', 'Guarulhos', 'Campinas', 'Nova Iguacu', 'Maceio', 'Sao Luis', 'Duque de Caxias', 'Natal', 'Teresina'],
    'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar'],
    'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
    'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Dedougou', 'Kaya', 'Dori', 'Tenkodogo', 'Reo'],
    'Cambodia': ['Phnom Penh', 'Battambang', 'Siem Reap', 'Sihanoukville', 'Poipet', 'Kampong Cham', 'Kampong Speu', 'Kampot', 'Koh Kong', 'Kep'],
    'Cameroon': ['Douala', 'Yaounde', 'Garoua', 'Kousseri', 'Bamenda', 'Maroua', 'Bafoussam', 'Mokolo', 'Ngaoundere', 'Bertoua'],
    'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Mississauga', 'Winnipeg', 'Quebec City', 'Hamilton', 'Brampton', 'Surrey', 'Laval', 'Halifax', 'London', 'Markham', 'Vaughan', 'Gatineau', 'Longueuil', 'Burnaby'],
    'China': ['Shanghai', 'Beijing', 'Tianjin', 'Guangzhou', 'Shenzhen', 'Wuhan', 'Dongguan', 'Hong Kong', 'Chongqing', 'Chengdu', 'Nanjing', 'Taipei', 'Nanchong', 'Xi\'an', 'Shenyang', 'Hangzhou', 'Harbin', 'Taiyuan', 'Suzhou', 'Zhengzhou', 'Changsha', 'Dalian'],
    'Colombia': ['Bogota', 'Medellin', 'Cali', 'Barranquilla', 'Cartagena', 'Cucuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibague'],
    'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula', 'Sesvete', 'Karlovac', 'Varazdin'],
    'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos', 'Kyrenia', 'Protaras', 'Morphou', 'Aradippou', 'Paralimni'],
    'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc', 'Usti nad Labem', 'Hradec Kralove', 'Ceske Budejovice', 'Pardubice'],
    "Côte d'Ivoire": ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro', 'Divo', 'Korhogo', 'Man'],
    'DR Congo': ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Goma', 'Tshikapa', 'Kolwezi', 'Likasi'],
    'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Vejle', 'Horsens'],
    'Dominican Republic': ['Santo Domingo', 'Santiago de los Caballeros', 'Santo Domingo Oeste', 'Santo Domingo Este', 'Santo Domingo Norte', 'San Pedro de Macoris', 'La Romana', 'Bella Vista', 'San Cristobal', 'Puerto Plata'],
    'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said', 'Suez', 'Luxor', 'El-Mahalla El-Kubra', 'Tanta', 'Asyut'],
    'El Salvador': ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Santa Tecla', 'Apopa', 'Delgado', 'Sonsonate', 'San Marcos'],
    'Eritrea': ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera', 'Barentu', 'Adi Keyh', 'Edd', 'Dekemhare', 'Akordat'],
    'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Kohtla-Jarve', 'Parnu', 'Viljandi', 'Rakvere', 'Maardu', 'Sillamae', 'Kuressaare'],
    'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekele', 'Nazret', 'Bahir Dar', 'Gonder', 'Dessie', 'Awasa', 'Jimma', 'Debre Zeyit'],
    'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyvaskyla', 'Lahti', 'Kuopio', 'Pori'],
    'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Etienne', 'Toulon', 'Grenoble', 'Dijon', 'Nimes', 'Angers', 'Villeurbanne'],
    'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hanover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Mannheim'],
    'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Ashiaman', 'Tema', 'Teshie', 'Cape Coast', 'Sekondi-Takoradi', 'Obuasi'],
    'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Rhodes', 'Ioannina', 'Chania', 'Chalcis'],
    'Haiti': ['Port-au-Prince', 'Carrefour', 'Delmas', 'Cap-Haitien', 'Petionville', 'Gonaives', 'Saint-Marc', 'Les Cayes', 'Verrettes', 'Port-de-Paix'],
    'Honduras': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Ciudad Choluteca', 'Comayagua', 'Puerto Cortes', 'La Lima', 'Danli'],
    'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pecs', 'Gyor', 'Nyiregyhaza', 'Kecskemet', 'Szekesfehervar', 'Szombathely'],
    'Iceland': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri', 'Reykjanesbaer', 'Garðabaer', 'Mosfellsbaer', 'Akranes', 'Selfoss', 'Njardvik'],
    'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Visakhapatnam', 'Indore', 'Thane', 'Bhopal', 'Pimpri-Chinchwad', 'Patna', 'Vadodara'],
    'Indonesia': ['Jakarta', 'Surabaya', 'Medan', 'Bandung', 'Bekasi', 'Palembang', 'Tangerang', 'Makassar', 'South Tangerang', 'Semarang', 'Depok', 'Padang', 'Denpasar', 'Bandar Lampung', 'Bogor', 'Malang', 'Pekanbaru', 'Batam', 'Banten', 'Surakarta'],
    'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia'],
    'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah', 'Kirkuk', 'Najaf', 'Karbala', 'Nasiriyah', 'Amara'],
    'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'],
    'Israel': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beersheba', 'Bnei Brak', 'Holon'],
    'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste', 'Brescia', 'Parma', 'Taranto', 'Prato', 'Modena'],
    'Japan': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Kobe', 'Kyoto', 'Fukuoka', 'Kawasaki', 'Saitama', 'Hiroshima', 'Sendai', 'Kitakyushu', 'Chiba', 'Sakai', 'Niigata', 'Hamamatsu', 'Shizuoka', 'Sagamihara', 'Okayama'],
    'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Al Quwaysimah', 'Aqaba', 'As Salt', 'Ar Ramtha', 'Al Mafraq', 'Madaba'],
    'Kazakhstan': ['Almaty', 'Karaganda', 'Shymkent', 'Taraz', 'Nur-Sultan', 'Kyzylorda', 'Semey', 'Aktobe', 'Uralsk', 'Pavlodar'],
    'Kenya': ['Nairobi', 'Mombasa', 'Nakuru', 'Eldoret', 'Kisumu', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kakamega'],
    'Kuwait': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'As Salimiyah', 'Sabah as Salim', 'Al Farwaniyah', 'Al Fahahil', 'Kuwait City', 'Ar Riqqah', 'Salwa'],
    'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Kara-Balta', 'Osh', 'Uzgen', 'Balykchy', 'Naryn'],
    'Laos': ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang', 'Xam Nua', 'Thakhek', 'Muang Xay', 'Xaignabouli', 'Muang Phonsavan', 'Vang Vieng'],
    'Latvia': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava', 'Jurmala', 'Ventspils', 'Rezekne', 'Jekabpils', 'Valmiera', 'Ogre'],
    'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Habbouch', 'Jounieh', 'Zahle', 'Baalbek', 'Byblos', 'Nabatieh'],
    'Liberia': ['Monrovia', 'Gbarnga', 'Bensonville', 'Harper', 'Buchanan', 'Zwedru', 'New Yekepa', 'Ganta', 'Robertsport', 'Tubmanburg'],
    'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Al Khums', 'Zawiya', 'Zliten', 'Sabha', 'Sirte', 'Al Bayda'],
    'Lithuania': ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys', 'Alytus', 'Dainava (Kaunas)', 'Marijampole', 'Mazeikiai', 'Jonava'],
    'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Dudelange', 'Schifflange', 'Bettembourg', 'Petange', 'Ettelbruck', 'Diekirch', 'Strassen', 'Bertrange'],
    'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara', 'Antsiranana', 'Antanifotsy', 'Ambovombe', 'Amparafaravola'],
    'Malaysia': ['Kuala Lumpur', 'Johor Bahru', 'Ipoh', 'Kuching', 'Petaling Jaya', 'Shah Alam', 'Kota Kinabalu', 'Sandakan', 'Seremban', 'Kuantan'],
    'Mali': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Kayes', 'Segou', 'Gao', 'Markala', 'Kolokani', 'Kati'],
    'Malta': ['Birkirkara', 'Qormi', 'Mosta', 'Zabbar', 'San Pawl il-Bahar', 'Saint John', 'Fgura', 'Zejtun', 'Sliema', 'Zebbug'],
    'Mauritania': ['Nouakchott', 'Nouadhibou', 'Nema', 'Kaedi', 'Rosso', 'Kiffa', 'Zouerate', 'Atar', 'Aleg', 'Tidjikdja'],
    'Mexico': ['Mexico City', 'Ecatepec', 'Guadalajara', 'Puebla', 'Ciudad Juarez', 'Tijuana', 'Ciudad Nezahualcoyotl', 'Monterrey', 'Leon', 'Zapopan', 'Naucalpan', 'Merida', 'Tlalnepantla', 'Chihuahua', 'San Luis Potosi', 'Aguascalientes', 'Hermosillo', 'Saltillo', 'Mexicali', 'Culiacan'],
    'Moldova': ['Chisinau', 'Tiraspol', 'Balti', 'Bender', 'Ribnita', 'Cahul', 'Ungheni', 'Soroca', 'Orhei', 'Dubasari'],
    'Mongolia': ['Ulaanbaatar', 'Erdenet', 'Darhan', 'Khovd', 'Olgii', 'Ulaangom', 'Moron', 'Suhbaatar', 'Bayankhongor', 'Dzuunharaa'],
    'Morocco': ['Casablanca', 'Rabat', 'Fes', 'Sale', 'Marrakesh', 'Agadir', 'Tangier', 'Meknes', 'Oujda', 'Kenitra'],
    'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala Porto', 'Quelimane', 'Tete', 'Xai-Xai', 'Maxixe'],
    'Myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago', 'Pathein', 'Monywa', 'Sittwe', 'Meiktila', 'Myeik'],
    'Nepal': ['Kathmandu', 'Pokhara', 'Patan', 'Biratnagar', 'Birganj', 'Dharan', 'Bharatpur', 'Janakpur', 'Dhangadhi', 'Butwal'],
    'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],
    'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Manukau', 'Waitakere', 'North Shore', 'Hamilton', 'Dunedin', 'Tauranga', 'Lower Hutt'],
    'Nicaragua': ['Managua', 'Leon', 'Masaya', 'Tipitapa', 'Chinandega', 'Matagalpa', 'Esteli', 'Granada', 'Ciudad Sandino', 'Juigalpa'],
    'Niger': ['Niamey', 'Zinder', 'Maradi', 'Agadez', 'Alaghsas', 'Tahoua', 'Dosso', 'Birni-N\'Konni', 'Tessaoua', 'Gaya'],
    'Nigeria': ['Lagos', 'Kano', 'Ibadan', 'Kaduna', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Jos'],
    'North Korea': ['Pyongyang', 'Hamhung', 'Nampo', 'Hungnam', 'Kaesong', 'Wonsan', 'Chongjin', 'Sinuiju', 'Haeju', 'Kanggye'],
    'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromso', 'Sarpsborg'],
    'Oman': ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Suhar', 'As Suwayq', 'Ibri', 'Saham', 'Barka', 'Rustaq'],
    'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Multan', 'Hyderabad', 'Gujranwala', 'Peshawar', 'Rahim Yar Khan', 'Quetta'],
    'Panama': ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Arraijan', 'Colon', 'Las Cumbres', 'La Chorrera', 'Pacora', 'Santiago'],
    'Paraguay': ['Asuncion', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiata', 'Lambare', 'Fernando de la Mora', 'Limpio', 'Nemby', 'Encarnacion'],
    'Peru': ['Lima', 'Arequipa', 'Callao', 'Trujillo', 'Chiclayo', 'Iquitos', 'Huancayo', 'Piura', 'Chimbote', 'Cusco'],
    'Philippines': ['Quezon City', 'Manila', 'Caloocan', 'Budta', 'Davao', 'Malingao', 'Cebu City', 'General Santos', 'Taguig', 'Pasig'],
    'Poland': ['Warsaw', 'Lodz', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
    'Portugal': ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setubal', 'Coimbra', 'Queluz', 'Funchal', 'Cacem', 'Vila Nova de Gaia'],
    'Qatar': ['Doha', 'Ar Rayyan', 'Umm Salal Muhammad', 'Al Wakrah', 'Al Khawr', 'Ash Shahaniyah', 'Dukhan', 'Musay\'id', 'Madinat ash Shamal', 'Al Wukayr'],
    'Romania': ['Bucharest', 'Iasi', 'Cluj-Napoca', 'Timisoara', 'Craiova', 'Constanta', 'Galati', 'Brasov', 'Ploiesti', 'Braila'],
    'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhny Novgorod', 'Samara', 'Omsk', 'Kazan', 'Chelyabinsk', 'Rostov-on-Don'],
    'Rwanda': ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi', 'Byumba', 'Cyangugu', 'Kibuye', 'Kibungo', 'Nzega'],
    'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Al-Ahsa', 'Ta\'if', 'Dammam', 'Buraydah', 'Khobar', 'Tabuk'],
    'Senegal': ['Dakar', 'Grand Dakar', 'Thies Nones', 'Saint-Louis', 'Ziguinchor', 'Touba', 'Kaolack', 'Mbour', 'Diourbel', 'Louga'],
    'Sierra Leone': ['Freetown', 'Bo', 'Kenema', 'Koidu', 'Makeni', 'Lunsar', 'Port Loko', 'Waterloo', 'Kabala', 'Magburaka'],
    'Singapore': ['Singapore', 'Woodlands', 'Jurong West', 'Tampines', 'Sengkang', 'Hougang', 'Yishun', 'Choa Chu Kang', 'Bukit Merah', 'Bukit Batok'],
    'Slovakia': ['Bratislava', 'Kosice', 'Presov', 'Nitra', 'Zilina', 'Banska Bystrica', 'Trnava', 'Martin', 'Trencin', 'Poprad'],
    'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Kamnik'],
    'Somalia': ['Mogadishu', 'Hargeysa', 'Berbera', 'Kismayo', 'Marka', 'Jamaame', 'Baidoa', 'Burao', 'Bosaso', 'Afgooye'],
    'South Africa': ['Cape Town', 'Durban', 'Johannesburg', 'Soweto', 'Pretoria', 'Port Elizabeth', 'Pietermaritzburg', 'Benoni', 'Tembisa', 'Vereeniging'],
    'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Goyang', 'Seongnam'],
    'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Murcia', 'Palma', 'Las Palmas de Gran Canaria', 'Bilbao'],
    'Sri Lanka': ['Colombo', 'Galkissa', 'Moratuwa', 'Jaffna', 'Negombo', 'Pita Kotte', 'Sri Jayewardenepura Kotte', 'Kandy', 'Trincomalee', 'Kalmunai'],
    'Sudan': ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'Al-Ubayyid', 'Kusti', 'Wad Madani', 'El Obeid', 'El Geneina', 'Ad-Damazin'],
    'Sweden': ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Vasteras', 'Orebro', 'Linkoping', 'Helsingborg', 'Jonkoping', 'Norrkoping'],
    'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel/Bienne'],
    'Syria': ['Aleppo', 'Damascus', 'Homs', 'Hama', 'Latakia', 'Dayr az Zawr', 'Ar Raqqah', 'Al Bab', 'Idlib', 'Duma'],
    'Tajikistan': ['Dushanbe', 'Khujand', 'Kulob', 'Qurghonteppa', 'Istaravshan', 'Konibodom', 'Kofarnihon', 'Tursunzoda', 'Isfara', 'Panjakent'],
    'Tanzania': ['Dar es Salaam', 'Mwanza', 'Zanzibar', 'Arusha', 'Mbeya', 'Morogoro', 'Tanga', 'Dodoma', 'Kigoma', 'Moshi'],
    'Thailand': ["Bangkok", "Nonthaburi", "Samut Prakan", "Chiang Mai", "Udon Thani", "Nakhon Ratchasima", "Hat Yai", "Pak Kret", "Si Racha", "Phra Pradaeng", "Lampang", "Khon Kaen", "Surat Thani", "Nakhon Si Thammarat", "Ubon Ratchathani", "Pattaya", "Nakhon Sawan", "Chiang Rai", "Songkhla", "Phitsanulok"],
    'Togo': ['Lome', 'Sokode', 'Kara', 'Atakpame', 'Palime', 'Bassar', 'Tsevie', 'Aneho', 'Sansanne-Mango', 'Dapaong'],
    'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Bizerte', 'Gabes', 'Aryanah', 'Gafsa', 'El Mourouj'],
    'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Cankaya', 'Antalya', 'Bagcilar'],
    'Turkmenistan': ['Ashgabat', 'Turkmenabat', 'Dasoguz', 'Mary', 'Balkanabat', 'Bayramaly', 'Türkmenbaşy', 'Tejen', 'Abadan', 'Yolöten'],
    'Uganda': ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Bwizibwera', 'Mbale', 'Mukono', 'Kasese', 'Masaka'],
    'Ukraine': ['Kiev', 'Kharkiv', 'Dnipro', 'Odessa', 'Donetsk', 'Zaporizhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv', 'Mariupol'],
    'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras al-Khaimah', 'Al Fujayrah', 'Umm al-Quwain', 'Khor Fakkan', 'Dibba Al-Fujairah'],
    'United Kingdom': ['London', 'Birmingham', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Edinburgh', 'Bristol', 'Manchester', 'Leicester'],
    'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Uruguay': ['Montevideo', 'Salto', 'Paysandu', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembo', 'Melo', 'Mercedes', 'Artigas'],
    'Uzbekistan': ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Nukus', 'Bukhara', 'Qarshi', 'Kokand', 'Chirchiq', 'Fergana'],
    'Venezuela': ['Caracas', 'Maracaibo', 'Maracay', 'Valencia', 'Barquisimeto', 'Ciudad Guayana', 'Barcelona', 'Maturin', 'Puerto La Cruz', 'Petare'],
    'Vietnam': ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Da Nang', 'Bien Hoa', 'Hue', 'Nha Trang', 'Can Tho', 'Rach Gia', 'Quy Nhon'],
    'Yemen': ['Sanaa', 'Al Hudaydah', 'Taizz', 'Aden', 'Al Mukalla', 'Ibb', 'Dhamar', 'Amran', 'Sayyan', 'Zabid'],
    'Zambia': ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola', 'Mufulira', 'Luanshya', 'Livingstone', 'Kasama', 'Chipata'],
    'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo', 'Chinhoyi']
}

common_baby_names = ['Liam', 'Olivia', 'Noah', 'Emma', 'Oliver', 'Ava', 'Isabella', 'Sophia', 'Mia', 'Charlotte',
                    'Amelia', 'Harper', 'Evelyn', 'Abigail', 'Emily', 'Elizabeth', 'Mila', 'Ella', 'Avery', 'Sofia',
                    'Camila', 'Aria', 'Scarlett', 'Victoria', 'Madison', 'Luna', 'Grace', 'Chloe', 'Penelope', 'Lily',
                    'Zoey', 'Riley', 'Nora', 'Aubrey', 'Hannah', 'Layla', 'Lillian', 'Addison', 'Eleanor', 'Natalie',
                    'Zoe', 'Stella', 'Hazel', 'Ellie', 'Paisley', 'Audrey', 'Skylar', 'Violet', 'Claire', 'Bella',
                    'Aurora', 'Lucy', 'Anna', 'Savannah', 'Maya', 'Genesis', 'Naomi', 'Valentina', 'Nova', 'Ruby',
                    'Eva', 'Alice', 'Lucia', 'Isabelle', 'Rose', 'Alyssa', 'Lyla', 'Ariana', 'Adeline', 'Mackenzie',
                    'Kylie', 'Gabriella', 'Autumn', 'Piper', 'Serenity', 'Allison', 'Arianna', 'Sarah', 'Taylor',
                    'Eliana', 'Maria', 'Gianna', 'Willow', 'Cora', 'Katherine', 'Emery', 'Adalynn', 'Kaylee', 'Brielle',
                    'Faith', 'Leah', 'Annabelle', 'Alexa', 'Madeline', 'Aubree', 'Jocelyn', 'Aaliyah', 'Londyn',
                    'Morgan', 'Harmony', 'Melanie', 'Diana', 'Liliana', 'Makayla', 'Laila', 'Daniela', 'Jade', 'Adalyn',
                    'Ashley', 'Alexandra', 'Amina', 'Elise', 'Jasmine', 'Amara', 'Daisy', 'Kimberly', 'Valerie',
                    'Melody', 'Alina', 'Ariella', 'Molly', 'Amanda', 'Sage', 'Kinsley', 'Lia', 'Nicole', 'Zara',
                    'Brooke', 'Noelle', 'Sara', 'Elliana', 'Skyler', 'Danielle', 'Mckenzie', 'Nadia', 'Hope', 'Erin',
                    'Nina', 'Raegan', 'Daniella', 'Jordyn', 'Maddison', 'Jennifer', 'Gracie', 'Keira', 'Harley',
                    'Amy', 'Kaitlyn', 'Camilla', 'Lena', 'Lucille', 'Eliza', 'Kate', 'Isabel', 'Summer', 'Maggie',
                    'Hayden', 'Makenzie', 'Amiyah', 'Kennedy', 'Miranda', 'Catherine', 'Paris', 'Sienna', 'Lilliana',
                    'Joanna', 'Dream', 'Rory', 'Arielle', 'Liana']

common_last_names = ['Adams', 'Aguilar', 'Aguirre', 'Aksornvithayakul', 'Alatorre', 'Alexander', 'Allen', 'Alvarez',
                    'Anderson', 'Andersson', 'Andrade', 'Andreev', 'Baek', 'Bailey', 'Baker', 'Barajas', 'Barnes',
                    'Barrios', 'Bauer', 'Becker', 'Bell', 'Beltran', 'Bengtsson', 'Benitez', 'Bennett', 'Berg',
                    'Bermudez', 'Black', 'Bogdanov', 'Boonkum', 'Boyd', 'Brooks', 'Brown', 'Bryant', 'Burns', 'Bustos',
                    'Butler', 'Cabello', 'Cabrera', 'Calderon', 'Campbell', 'Campos', 'Carrillo', 'Carter', 'Castillo',
                    'Castro', 'Cavazos', 'Cedillo', 'Cervantes', 'Chaiyachet', 'Chaiyaporn', 'Chalermphong',
                    'Chantanapong', 'Chantanapongwanit', 'Chavez', 'Chen', 'Chirathivat', 'Cho', 'Choi',
                    'Choothamanivong', 'Chotanaphan', 'Cisneros', 'Clark', 'Cole', 'Coleman', 'Collins', 'Contreras',
                    'Cook', 'Cooper', 'Cordova', 'Coronado', 'Cortez', 'Cox', 'Crawford', 'Cruz', 'Daniels', 'Davis',
                    'Delgado', 'Deng', 'Diaz', 'Dixon', 'Duarte', 'Dunn', 'Dąbrowski', 'Edwards', 'Egorov', 'Ellis',
                    'Eriksson', 'Espinosa', 'Espinoza', 'Esquivel', 'Estrada', 'Evans', 'Ferguson', 'Fernandez',
                    'Figueroa', 'Fischer', 'Fisher', 'Flores', 'Ford', 'Foster', 'Freeman', 'Fuentes', 'Galindo',
                    'Gallardo', 'Gao', 'Garcia', 'Gibson', 'Gomez', 'Gonzalez', 'Gordon', 'Grabowski', 'Graham',
                    'Granados', 'Grant', 'Gray', 'Green', 'Griffin', 'Guerra', 'Guerrero', 'Guo', 'Gustafsson',
                    'Gutierrez', 'Guzman', 'Hall', 'Hamilton', 'Han', 'Hansson', 'Harris', 'Harrison', 'Hartmann',
                    'Hawkins', 'Hayashi', 'Hayes', 'He', 'Henderson', 'Henry', 'Hernandez', 'Herrera', 'Hicks',
                    'Hidalgo', 'Hill', 'Hoffmann', 'Holmes', 'Howard', 'Hu', 'Huang', 'Hughes', 'Hunt', 'Hunter',
                    'Hurtado', 'Hwang', 'Ibarra', 'Inoue', 'Ito', 'Ivanov', 'Jackson', 'James', 'Jang', 'Jankowski',
                    'Jansson', 'Jaramillo', 'Jareonvithayakul', 'Jenkins', 'Jeong', 'Jimenez', 'Johansson', 'Johnson',
                    'Jones', 'Jonsson', 'Jordan', 'Kaczmarek', 'Kamiński', 'Kang', 'Karlsson', 'Karpov', 'Kato', 'Kelly',
                    'Kennedy', 'Kim', 'Kimura', 'King', 'Klein', 'Knight', 'Ko', 'Kobayashi', 'Koch', 'Kowalczyk',
                    'Kowalski', 'Kozlov', 'Kozłowski', 'Krause', 'Krawczyk', 'Kuznetsov', 'Kwiatkowski', 'Kwon', 'Lara',
                    'Larsson', 'Lebedev', 'Lee', 'Leon', 'Lewis', 'Li', 'Lim', 'Lin', 'Lindberg', 'Lira', 'Liu', 'Loera',
                    'Lomeli', 'Long', 'Lopez', 'Luna', 'Lundberg', 'Ma', 'Madrigal', 'Magana', 'Maldonado', 'Marshall',
                    'Martin', 'Martinez', 'Mason', 'Matsumoto', 'Mattsson', 'Mazur', 'McDonald', 'Medina', 'Medrano',
                    'Mejia', 'Melendez', 'Mendez', 'Mendoza', 'Mikhailov', 'Miller', 'Mills', 'Miramontes', 'Miranda',
                    'Mireles', 'Mitchell', 'Molina', 'Montes', 'Montoya', 'Moore', 'Morales', 'Moreno', 'Morgan',
                    'Morozov', 'Morris', 'Munoz', 'Murphy', 'Murray', 'Myers', 'Müller', 'Nakamura', 'Narongdej',
                    'Navarro', 'Nelson', 'Neumann', 'Nichols', 'Nikolaev', 'Nilsson', 'Nim-anong', 'Novikov', 'Nowak',
                    'Nowakowski', 'Nunez', 'Ochoa', 'Oh', 'Olivares', 'Olivarez', 'Olofsson', 'Olsson', 'Orlov', 'Ortiz',
                    'Owens', 'Pacheco', 'Palacios', 'Palmer', 'Park', 'Parker', 'Patterson', 'Pawłowski', 'Pena', 'Perez',
                    'Perkins', 'Perry', 'Persson', 'Peterson', 'Petrov', 'Pettersson', 'Phillips', 'Phrommala', 'Pineda',
                    'Piotrowski', 'Pizarro', 'Popov', 'Porter', 'Powell', 'Price', 'Quinones', 'Quintero', 'Ramirez',
                    'Ramos', 'Rangel', 'Rattanapong', 'Reed', 'Reyes', 'Reyna', 'Reynolds', 'Rice', 'Richardson',
                    'Richter', 'Rincon', 'Rios', 'Rivera', 'Roberts', 'Robertson', 'Robinson', 'Rocha', 'Rodriguez',
                    'Rogers', 'Rojas', 'Rosales', 'Rose', 'Ross', 'Ruiz', 'Russell', 'Ryu', 'Saldana', 'Salgado',
                    'Sanchez', 'Sanders', 'Sandoval', 'Santana', 'Santillan', 'Santos', 'Sasaki', 'Sato', 'Saucedo',
                    'Schmid', 'Schmidt', 'Schneider', 'Schubert', 'Schulz', 'Schumacher', 'Scott', 'Segura', 'Sepulveda',
                    'Serrano', 'Shaw', 'Shibata', 'Shimizu', 'Shin', 'Silva', 'Simmons', 'Simpson', 'Smirnov', 'Smith',
                    'Sokolov', 'Solis', 'Song', 'Sonthichai', 'Soto', 'Sriporn', 'Stepanov', 'Stevens', 'Stewart', 'Stone',
                    'Sukchareon', 'Sullivan', 'Sun', 'Sustaita', 'Suzuki', 'Svensson', 'Szymański', 'Takahashi', 'Tamez',
                    'Tanaka', 'Taylor', 'Thomas', 'Thompson', 'Thongchareon', 'Thongkam', 'Torres', 'Tovar', 'Trevino',
                    'Trujillo', 'Tucker', 'Turner', 'Valdez', 'Valencia', 'Valenzuela', 'Valle', 'Varela', 'Vargas',
                    'Vasquez', 'Velasquez', 'Vergara', 'Villa', 'Villalobos', 'Villanueva', 'Villareal', 'Villegas',
                    'Volkov', 'Wagner', 'Walker', 'Wallace', 'Wang', 'Ward', 'Warren', 'Washington', 'Watanabe', 'Watson',
                    'Webb', 'Weber', 'Wells', 'West', 'White', 'Williams', 'Wilson', 'Wiśniewski', 'Wojciechowski', 'Wood',
                    'Woods', 'Wright', 'Wu', 'Wójcik', 'Xu', 'Yamada', 'Yamaguchi', 'Yamamoto', 'Yang', 'Yoo', 'Yoon',
                    'Yoshida', 'Young', 'Zaitsev', 'Zamora', 'Zavala', 'Zhang', 'Zhao', 'Zhou', 'Zieliński']

common_adjectives_for_people = ['adaptable', 'adventurous', 'aloof', 'ambitious', 'anti-social', 'anxious', 'apathetic',
                                'arrogant', 'attentive', 'blunt', 'boring', 'calm', 'caring', 'cautious', 'charismatic',
                                'cheerful', 'clever', 'closed-minded', 'compassionate', 'confident', 'conventional',
                                'cooperative', 'courageous', 'courteous', 'cowardly', 'creative', 'cruel', 'curious',
                                'daring', 'deceitful', 'dependent', 'depressed', 'determined', 'diligent', 'dishonest',
                                'disloyal', 'disrespectful', 'distracted', 'distrustful', 'eager', 'egotistical',
                                'eloquent', 'empathetic', 'energetic', 'enthusiastic', 'fake', 'foolish', 'forgetful',
                                'fragile', 'friendly', 'generous', 'gentle', 'genuine', 'gloomy', 'grateful', 'greedy',
                                'gregarious', 'harsh', 'helpful', 'helpless', 'honest', 'hostile', 'humble', 'idealistic',
                                'immature', 'impatient', 'inarticulate', 'inconsiderate', 'indecisive', 'independent',
                                'indifferent', 'innovative', 'insecure', 'insensitive', 'intolerant', 'introverted',
                                'irrational', 'irresponsible', 'kind', 'lazy', 'lethargic', 'lively', 'loyal', 'mature',
                                'modest', 'negative', 'neglectful', 'negligent', 'nervous', 'observant', 'obstinate',
                                'open-minded', 'optimistic', 'outgoing', 'passionate', 'patient', 'pessimistic', 'polite',
                                'positive', 'practical', 'reckless', 'reliable', 'reserved', 'resilient', 'resourceful',
                                'respectful', 'responsible', 'rough', 'rude', 'self-motivated', 'selfish', 'sensible',
                                'sensitive', 'shy', 'simple-minded', 'sincere', 'sluggish', 'sociable', 'stubborn',
                                'sympathetic', 'tactful', 'talented', 'thoughtful', 'timid', 'tolerant', 'treacherous',
                                'trustworthy', 'unfeeling', 'ungrateful', 'unhelpful', 'unimaginative', 'unobservant',
                                'unreliable', 'unsympathetic', 'untalented', 'vain', 'wise']

common_email_domains = [ "gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "aol.com", "icloud.com", "protonmail.com",
                        "yandex.com", "zoho.com", "mail.com", "gmx.com", "inbox.com", "mail.ru", "qq.com", "163.com",
                        "126.com", "sina.com", "outlook.jp", "naver.com", "daum.net", "naver.jp", "rocketmail.com",
                        "live.com", "me.com", "fastmail.com", "disposable.com", "apple.com", "msn.com", "earthlink.net"]


unique_names = []
repeated_names = []

for name in common_adjectives_for_people:
    if name not in unique_names:
        unique_names.append(name)
    else:
        repeated_names.append(name)

unique_names.sort()

# Print the final list of unique nationalities
print([name.lower() for name in unique_names])
print()
print(repeated_names)